# RainbowGear config
# Lore is the lore required on leather armor for it to rainbowgear
# Colors is how many possible colors armor can have (lower = more efficient)
# RefreshRate is how many ticks armor is updated (higher = more efficient)
# Cycle is (Colors * (RefreshRate / 20). This is how many seconds it takes to cycle once

Lore: 'rainbow'
Engine:
  Colors: 64
  RefreshRate: 5
  PrintInfo: true
Lang:
    Init: '&3Rainbow armor activated, logout to deactivate!'
    Gear: '&3Added lore to %armorpiece' 