# RBGArmor config
# Colors is how many possible colors armor can have (lower = more efficient)
# RefreshRate is how many ticks armor is updated (higher = more efficient)
Core:
  Colors: 64
  RefreshRate: 5
  Debug: false
